### ISSUE TITLE
calibration parameters

### ISSUE THREAD

**Issue by ed-fish** [hahnyuan/PTQ4ViT#12]
Hi, may I ask for more details on what this function does?

```py
   def _initialize_calib_parameters(self):
        """ 
        set parameters for feeding calibration data
        """
        self.calib_size = int(self.raw_input.shape[0])
        self.calib_batch_size = int(self.raw_input.shape[0])
        while True:
            numel = (2*(self.raw_input.numel()+self.raw_out.numel()) /
                     self.calib_size*self.calib_batch_size)  # number of parameters on GPU
            self.parallel_eq_n = int((15*1024*1024*1024/4)//numel)
            if self.parallel_eq_n <= 1:
                self.calib_need_batching = True
                self.calib_batch_size //= 2
            else:
                break
```

I am adapting your code for 1DConvolution and the ```self.parallel_eq_n``` is multiplying by the output channels of the weights and causing memory issues. If you could provide further details it would be really helpful. Thankyou. Ed

**Comment by SuperVan-Young** [comment]
This function maximize parallelism (`calib_batch_size` and `parallel_eq_n`) for fast calibration under the constarints of GPU memory. The constant `15*1024*1024*1024/4` targets our V100 platform with 32GB GPU memory, and we want to allocate half of the memory for activation values. You might adjust this constant lower to fit your platform.

**Comment by ed-fish** [comment]
Thank you for your fast response. I am trying to run the code on a single 24GB GPU - What value should I put for ```self.parallel_eq_n```

**Comment by ed-fish** [comment]
Not to worry - I figured out the best setting. Thanks again for you work.

**Comment by haiduo** [comment]
> Hi, may I ask for more details on what this function does?
> 
> ```python
>    def _initialize_calib_parameters(self):
>         """ 
>         set parameters for feeding calibration data
>         """
>         self.calib_size = int(self.raw_input.shape[0])
>         self.calib_batch_size = int(self.raw_input.shape[0])
>         while True:
>             numel = (2*(self.raw_input.numel()+self.raw_out.numel()) /
>                      self.calib_size*self.calib_batch_size)  # number of parameters on GPU
>             self.parallel_eq_n = int((15*1024*1024*1024/4)//numel)
>             if self.parallel_eq_n <= 1:
>                 self.calib_need_batching = True
>                 self.calib_batch_size //= 2
>             else:
>                 break
> ```
> 
> I am adapting your code for 1DConvolution and the `self.parallel_eq_n` is multiplying by the output channels of the weights and causing memory issues. If you could provide further details it would be really helpful. Thankyou. Ed

The main purpose of this code is to dynamically adjust the calibration batch size to maximize GPU utilization. By reducing the batch size, when the processing of a single batch cannot effectively utilize GPU resources, the workload of parallel processing can be increased, thereby improving efficiency.
