### ISSUE TITLE
Why i cant get the accuracy in README.txt

### ISSUE THREAD

**Issue by buzhou1** [hahnyuan/PTQ4ViT#21]
I just run the code with any changed and I got the different accuracy like:
0.7599 as vit_small_patch32_224 (float)
PTQ4VIT: 0.7541 as vit_small_patch32_224 (w8,a8)      BasePTQ: 0.74856 vit_small_patch32_224 (w8,a8)
PTQ4VIT: 0.7174 as vit_small_patch32_224 (w6,a6)      BasePTQ: 0.64272 vit_small_patch32_224 (w6,a6)

and other models have the same problem 
I didnt change any in original code
Is it because we're using different libraries? Versions of my library:
Python==3.10.6
timm==0.6.13
torch==1.12.1

**Comment by XingchenSong1116** [comment]
Hi, i also met this problem, may i ask have you fix this problem yet?

**Comment by SuperVan-Young** [comment]
Hi there. I've rerun the script and here's the accuracy result for vit_small_patch32_224:
PTQ4VIT: 0.75528 as vit_small_patch32_224 (w8,a8) BasePTQ: 0.74852 vit_small_patch32_224 (w8,a8)
PTQ4VIT: 0.72068 as vit_small_patch32_224 (w6,a6) BasePTQ: 0.64008 vit_small_patch32_224 (w6,a6)  
It's different from both buzhou's result and the results in README.txt.

I'm using exactly the same conda environment in which we report the experiment result in our ECCV paper. The version of key libraries are as follow:
- python: 3.7.11
- timm: 0.4.12
- pytorch: 1.10.0
- torchvision: 0.11.1
What's more, the original code / original model in float / imagenet dataset / V100 GPU remains the same as before.

The only thing that changes is the cuda version. Originally the cuda version on our GPU server is 10.2, but right now it has been updated to 11.6. I suspect this is the reason for the experiment result mismatch. Probably cuda has modified the implementation of certain operators, which could potentially affect numerical stability. Next we'll try using older version of cuda to rerun the experiment, and see if it's the source of the problem.
